/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-error": "#690005",
              "surface": "rgba(var(--color-surface), <alpha-value>)",
              "secondary-fixed": "#e5e2e1",
              "primary-fixed": "#f7e600",
              "on-tertiary": "#003737",
              "on-tertiary-container": "#007070",
              "on-background": "#e2e2e2",
              "surface-dim": "#131313",
              "inverse-surface": "#e2e2e2",
              "on-primary-fixed-variant": "#4e4800",
              "background": "rgba(var(--color-background), <alpha-value>)",
              "surface-container-lowest": "#0e0e0e",
              "on-surface-variant": "rgba(var(--color-on-surface-variant), <alpha-value>)",
              "primary": "rgba(var(--color-primary), <alpha-value>)",
              "tertiary-fixed-dim": "#49dada",
              "surface-container-low": "#1b1b1b",
              "on-secondary": "#313030",
              "on-primary-fixed": "#1f1c00",
              "error-container": "#93000a",
              "secondary-container": "#474746",
              "tertiary-fixed": "#6cf7f7",
              "on-secondary-container": "#b7b5b4",
              "primary-container": "#f7e600",
              "outline-variant": "#4a4731",
              "on-secondary-fixed-variant": "#474746",
              "on-error-container": "#ffdad6",
              "inverse-primary": "#676000",
              "outline": "#969177",
              "tertiary": "#ffffff",
              "primary-fixed-dim": "#d8ca00",
              "on-tertiary-fixed": "#002020",
              "surface-tint": "#d8ca00",
              "surface-container-highest": "rgba(var(--color-surface-container-highest), <alpha-value>)",
              "inverse-on-surface": "#303030",
              "on-tertiary-fixed-variant": "#004f50",
              "secondary": "#c8c6c5",
              "on-primary-container": "#6e6600",
              "error": "#ffb4ab",
              "surface-bright": "#393939",
              "on-surface": "#ffffff",
              "tertiary-container": "#6cf7f7",
              "on-secondary-fixed": "#1c1b1b",
              "secondary-fixed-dim": "#c8c6c5",
              "surface-container": "#1f1f1f",
              "on-primary": "#000000",
              "surface-container-high": "rgba(var(--color-surface-container-high), <alpha-value>)",
              "surface-variant": "#353535"
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "spacing": {
              "section-gap": "64px",
              "stack-sm": "12px",
              "stack-md": "20px",
              "glass-padding": "24px",
              "container-padding": "40px",
              "unit": "8px"
      },
      "fontFamily": {
              "h1": ["Outfit"],
              "label-caps": ["Inter"],
              "h1-mobile": ["Outfit"],
              "display-clock": ["Outfit"],
              "display-clock-mobile": ["Outfit"],
              "body-lg": ["Inter"],
              "body-md": ["Inter"],
              "h2": ["Outfit"],
              "s-label-sm": ["JetBrains Mono"],
              "s-body-md": ["Geist"],
              "s-headline-lg": ["Space Grotesk"],
              "s-headline-lg-mobile": ["Space Grotesk"],
              "s-display-lg": ["Space Grotesk"]
      },
      "fontSize": {
              "h1": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
              "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
              "h1-mobile": ["32px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
              "display-clock": ["120px", { "lineHeight": "120px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
              "display-clock-mobile": ["72px", { "lineHeight": "72px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
              "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
              "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "h2": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
              "s-label-sm": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
              "s-body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
              "s-headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
              "s-headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
              "s-display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
